export default {
  gigastomp: { 
    tiles: [['monster_0_s_a','monster_0_s_b'],['monster_0_s_c','monster_0_s_d']],
    isPlayer: true,
    health: 40,
    maxHealth: 40,
    healthRegenRate: 0.5,
    energy: 20,
    maxEnergy: 20,
    energyRegenRate: 0.5,
    ai: 'waitForPlayerAction',
    description: "It's you. Rarrr",
    stomps: true,
    smashes: true,
    smashDamage: 12,
    swims: true,
    fg: '#FF77A8',
  },
  tanks: { 
    tiles: [['tanks_0']], 
    ai: 'huntAndShoot',
    description: "Tanks",
    drives: true,
    range: 3,
    shootAnimation: 'shots',
    health: 1,
    attack: 1,
    becomes: 'tankDust',
    stompable: true,
    fg: '#C2C3C7',
  },
  maserTank: { 
    tiles: [['maser_tank_0']], 
    ai: 'huntAndShoot',
    description: "Experimental MASER Tank",
    drives: true,
    range: 3,
    shootAnimation: 'beam',
    health: 1,
    attack: 2,
    becomes: 'tankDust',
    stompable: true,
    fg: '#C2C3C7',
  },
  betterGigastomp: {
    tiles: [['meka_a','meka_b'],['meka_c','meka_d']],
    ai: 'sleep',
    description: "Model BG01 - Codename: Better-Gigastomp",
    stomps: true,
    smashes: true,
    smashDamage: 5,
    shootAnimation: 'beam',
    health: 40,
    range: 4,
    attack: 4,
    becomes: 'scrap',
    isBoss: true,
    fg: '#C2C3C7',
  }
}


