export default {
  nullTerrain:  {
    tiles: ['null'], 
  },
  ground: {
    tiles: ['ground'], 
    walkable: true, 
    stompable: true,
  },
  sand: {
    description: 'Sand',
    tiles: ['sand'],
    fg: '#FFEC27', 
    walkable: true, 
    drivable: true, 
    stompable: true,
  },
  tankDust: {
    description: 'Tank dust',
    tiles: ['dust'], 
    walkable: true, 
    drivable: true, 
    stompable: true,
  },
  road: {
    description: 'A road',
    tiles: ['road'], 
    walkable: true, 
    drivable: true, 
    stompable: true,
  },
  water: {
    description: 'Water',
    tiles: ['water'], 
    fg: '#29ADFF', 
    bg: '#1D2B53', 
    walkable: true,
    swimmable: true
  },
  houses: {
    description: 'Houses',
    tiles: ['houses_0', 'houses_1'],
    fg: '#FFCCAA', 
    walkable: true, 
    stompable: true,
    destroysTo: 'rubble',
  },
  shortBldg: {
    description: 'Buildings',
    tiles: ['short_bldg_0', 'short_bldg_1'],
    fg: '#FFF1E8', 
    walkable: true, 
    stompable: true,
    destroysTo: 'rubble',
  },
  tallBldg: {
    description: 'Towers',
    tiles: ['tall_bldg_0','tall_bldg_1','tall_bldg_2','tall_bldg_3'],
    fg: '#29ADFF', 
    walkable: true, 
    isCover: true,
    collapses: true,
    smashable: true,
    destroysTo: 'rubble',
  },
  chemBldg: {
    description: 'Refinery',
    tiles: ['chem_bldg_0','chem_bldg_1'],
    fg: '#FFA300', 
    walkable: true, 
    stompable: true,
    explodes: true,
    explodeDamage: 3,
    destroysTo: 'rubble',
  },
  rubble: {
    description: 'Rubble',
    tiles: ['rubble_0','rubble_1','rubble_2'],
    walkable: true, 
    stompable: true,
    drivable: false,
    explodes: false,
    collapses: false,
    isPowerUp: false,
    isCover: false,
    electrified: false,
    destroysTo: null,
  },
  scrap: {
    description: 'Scrap Pile',
    tiles: ['rubble_0','rubble_1','rubble_2'],
    walkable: true, 
    stompable: true,
    drivable: false,
    explodes: false,
    collapses: false,
    isPowerUp: false,
    isCover: false,
    electrified: false,
    destroysTo: null,
  },
  debris: {
    description: 'Natural debris',
    tiles: ['debris_0'],
    walkable: true, 
    stompable: true,
    drivable: false,
    explodes: false,
    collapses: false,
    isPowerUp: false,
    isCover: false,
    electrified: false,
    destroysTo: null,
  },
  coolingTower: {
    description: 'Nuclear plant',
    tiles: ['cooling_tower_0'], 
    fg: '#FFEC27', 
    walkable: true, 
    stompable: true,
    destroysTo: 'rubble',
  },
  powerline: {
    description: 'High-voltage lines',
    tiles: ['powerline_0'], 
    fg: '#FFEC27', 
    walkable: true, 
    stompable: true,
    electrified: true,
    elecDamage: 2,
    destroysTo: 'rubble',
  },
  park: {
    description: 'Trees',
    tiles: ['park_0','park_1'],
    fg: '#00E436', 
    walkable: true, 
    stompable: true,
    destroysTo: 'debris',
  },
  giantMelon: {
    description: 'Giant Melon',
    tiles: ['giant_melon'],
    fg: '#FFA300', 
    walkable: true, 
    stompable: true,
    isPowerUp: true,
    destroysTo: 'debris',
  },
  giantPeach: {
    description: 'Giant Peach',
    tiles: ['giant_peach'],
    fg: '#FFCCAA', 
    walkable: true, 
    stompable: true,
    isPowerUp: true,
    destroysTo: 'debris',
  },
  giantWatermelon: {
    description: 'Giant Watermelon',
    tiles: ['giant_watermelon'],
    fg: '#00E436', 
    walkable: true, 
    stompable: true,
    isPowerUp: true,
    destroysTo: 'debris',
  }
}